linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - goimports

    - bodyclose
    - canonicalheader
    - sqlclosecheck

    - tparallel
    - thelper
    - testpackage
