version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  format:
    cmds:
      - goimports -w -l .

  test:
    cmds:
      - go test -race ./...

  test:coverage:
    cmds:
      - go test -coverprofile=coverage.out ./...
