version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint run ./...

  format:
    cmds:
      - goimports -w -l .

  test-cmd:
    internal: true
    cmds:
      - go test {{ .flags }} ./...

  test:
    cmds:
      - task: test-cmd
        vars:
          flags: -race

  test:coverage:
    cmds:
      - task: test-cmd
        vars:
          flags: -coverprofile=coverage.out
